export const env = {
  NEXT_PUBLIC_BACKEND_SERVER_URL:
    process.env.NEXT_PUBLIC_BACKEND_SERVER_URL || "",
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL || "",

  // Azure Blob Storage (server-side only)
  AZURE_STORAGE_ACCOUNT_NAME: process.env.AZURE_STORAGE_ACCOUNT_NAME || "",
  AZURE_STORAGE_ACCOUNT_KEY: process.env.AZURE_STORAGE_ACCOUNT_KEY || "",
  AZURE_STORAGE_CONNECTION_STRING:
    process.env.AZURE_STORAGE_CONNECTION_STRING || "",
  AZURE_STORAGE_CONTAINER_NAME: process.env.AZURE_STORAGE_CONTAINER_NAME || "",
  AZURE_STORAGE_BLOB_ENDPOINT: process.env.AZURE_STORAGE_BLOB_ENDPOINT || "",

  // Database
  DATABASE_URL: process.env.DATABASE_URL || "",

  // Azure AD
  NEXT_PUBLIC_AZURE_AD_CLIENT_ID:
    process.env.NEXT_PUBLIC_AZURE_AD_CLIENT_ID || "",
  NEXT_PUBLIC_AZURE_AD_TENANT_ID:
    process.env.NEXT_PUBLIC_AZURE_AD_TENANT_ID || "",
  NEXT_PUBLIC_AZURE_AD_REDIRECT_URI:
    process.env.NEXT_PUBLIC_AZURE_AD_REDIRECT_URI || "",
  NEXT_PUBLIC_AZURE_AD_AUTHORITY:
    process.env.NEXT_PUBLIC_AZURE_AD_AUTHORITY || "",
};
