name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # Set this to your Azure Web App name
  REGISTRY_NAME: yourregistry.azurecr.io  # Set this to your Azure Container Registry

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY_NAME }}/frontend:${{ github.sha }}
        build-args: |
          NEXT_PUBLIC_BACKEND_SERVER_URL=${{ secrets.NEXT_PUBLIC_BACKEND_SERVER_URL }}
          NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_AZURE_AD_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AD_TENANT_ID=${{ secrets.NEXT_PUBLIC_AZURE_AD_TENANT_ID }}
          NEXT_PUBLIC_AZURE_AD_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_AZURE_AD_REDIRECT_URI }}
          NEXT_PUBLIC_AZURE_AD_AUTHORITY=${{ secrets.NEXT_PUBLIC_AZURE_AD_AUTHORITY }}
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.REGISTRY_NAME }}/frontend:${{ github.sha }}